"""initial tables

Revision ID: 7a0bcd581af5
Revises: 
Create Date: 2026-04-19 15:44:18.385132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0bcd581af5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('TILL_ROLL', 'CHARGER', 'SIM_CARD', 'OWN_STOCK_DEVICE', 'REFURB_BATTERY', 'CLEANING_PRODUCT', 'STICKER', name='item_category'), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battery_levels',
    sa.Column('status', sa.Enum('CHARGING', 'READY', 'IN_USE', name='battery_status'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_battery_quantity_non_negative'),
    sa.PrimaryKeyConstraint('status')
    )
    op.create_table('battery_updates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('CHARGING', 'READY', 'IN_USE', name='battery_status'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('recorded_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_battery_update_quantity_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('given_to', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('recorded_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_levels',
    sa.Column('category', sa.Enum('TILL_ROLL', 'CHARGER', 'SIM_CARD', 'OWN_STOCK_DEVICE', 'REFURB_BATTERY', 'CLEANING_PRODUCT', 'STICKER', name='item_category'), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_stock_quantity_non_negative'),
    sa.CheckConstraint('reorder_level >= 0', name='ck_stock_reorder_non_negative'),
    sa.PrimaryKeyConstraint('category', 'subtype')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('TILL_ROLL', 'CHARGER', 'SIM_CARD', 'OWN_STOCK_DEVICE', 'REFURB_BATTERY', 'CLEANING_PRODUCT', 'STICKER', name='item_category'), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=False),
    sa.Column('movement_type', sa.Enum('USED', 'RECEIVED', name='movement_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('given_to', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('recorded_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_transaction_quantity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('stock_levels')
    op.drop_table('device_transactions')
    op.drop_table('battery_updates')
    op.drop_table('battery_levels')
    op.drop_table('alerts')
    # Drop PostgreSQL enum types created alongside the tables above.
    sa.Enum(name='movement_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='item_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='battery_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
